name: pycofbuilder
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - panel
  - pip
  - python >= 3.10
  - pymatgen
  - scipy
  - simplejson
  - tqdm
  - ase
  - gemmi
